import type { Metadata } from "next";
import { Geist_Mono, Cairo } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Client from "./client";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

const cairo = Cairo({
  variable: "--font-cairo-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Syria Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <head></head>
      <body className={`${cairo.variable} ${geistMono.variable} antialiased`}>
        <Client>
          <Toaster richColors position="top-center" />
          {children}
        </Client>
      </body>
    </html>
  );
}
